title: Ciaanh's blog

baseurl: ""
url: "https://ciaanh.github.io"
twitter_username: ciaanh
github_username: ciaanh

#remote_theme: poole/lanyon
#remote_theme: Ciaanh/awesome-jekyll-theme
theme: dinky

google_analytics: UA-155086691-1
