title: Ciaanh's blog

baseurl: ""
url: "https://ciaanh.github.io"
twitter_username: ciaanh
github_username: ciaanh

#remote_theme: Ciaanh/awesome-jekyll-theme
#remote_theme: pages-themes/slate
remote_theme: cyevgeniy/jekyll-true-minimal


google_analytics: UA-155086691-1
